### ISSUE TITLE
Web3.jl does not work with the Infura API

### ISSUE THREAD

**Issue by loredanacirstea** [lambda-mechanics/Web3.jl#6]
Error when trying out any of the methods: 
```
KeyError: key "result" not found
getindex(::Dict{String,Any}, ::String) at dict.jl:477
jsonget(::String, ::Symbol) at Web3.jl:83
(::Web3.var"#3#5"{Web3.var"#3#4#6"{Symbol,Web3.var"#22#63"}})(::Web3Connection; raw::Bool) at Web3.jl:117
(::Web3.var"#3#5"{Web3.var"#3#4#6"{Symbol,Web3.var"#22#63"}})(::Web3Connection) at Web3.jl:117
top-level scope at dumpContract.jl:32
```

(I may look into it myself next week)

**Comment by zot** [comment]
Alright, I made an Infuria acct. I know I used it years ago -- maybe I didn't need an account for it to use it back then. I'll see what happens when I use this with Infuria...

**Comment by zot** [comment]
Apparently infuria doesn't like when you omit a request id so I just made an incrementing msgId variable. It's not safe for multithreading but at least it'll get the gears unblocked...
